export const LOAD_HOME = 'LOAD_HOME';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const HANDLE_UPDATE_CHANGE = 'HANDLE_UPDATE_CHANGE';
export const HANDLE_UPDATE_SUBMIT = 'HANDLE_UPDATE_SUBMIT';
